### ISSUE TITLE
Validate method invoke render method

### ISSUE THREAD

**Issue by Volodymyr128** [jurassix/react-validation-mixin#46]
`validate` method make components to be re-rendered, what is bad. It's bad because I need validation on   rendering, which creates infinite loop.

Is there any way to invoke `validate` without component re-rendering?

**Comment by jurassix** [comment]
This is by design. Validate is asynchronous and causes a re-render when completed. 

You have access to the __validation-strategy__ and can invoke `validate()` directly if you wish to avoid re-render; _this will not update the props passed to your component and could introduce hard to find bugs._

[Here is the API for invoking the validation directly:](https://github.com/jurassix/joi-validation-strategy/blob/master/src/joiValidationStrategy.js)

```javascript
validate(data = {}, joiSchema = {}, options = {}, callback)
```

**Comment by Volodymyr128** [comment]
Thanks for your support!

  I agree that's error-prone. But suppose you have a form and submit button, the button should be disabled if form is invalid. Moreover, form initial data comes from Store - user may input something, close the form and then return to submit it. Then you'll want to validate form from inside render method. Won't it be great to have some out-of-the-box validation strategy to validate without re-rendring? Or maybe there is more simple way?
