### ISSUE TITLE
Type of "children" property is too restrictive

### ISSUE THREAD

**Issue by martindederer** [jurassix/react-validation-mixin#64]
I suspect that the validation HOC's children property type definition is too restrictive. It causes warnings like

> Failed propType: Invalid prop `children` of type `object` supplied to `Validation(MyComponent)`, expected `array`

in my code base.

Currently it is limited to "PropTypes.array". Shouldn't it be 

> React.PropTypes.oneOfType([React.PropTypes.array, React.PropTypes.element])

instead? [According to the react docs](https://facebook.github.io/react/tips/children-props-type.html) the children property can be "array" or i guess "element". The latter is not stated explicitly though.

What do you think?

**Comment by jurassix** [comment]
@martindederer I think you are probably correct that we can remove the following lines:
* Remove the PropTypes all together
  * https://github.com/jurassix/react-validation-mixin/blob/master/src/components/validationMixin.js#L127
* Remove the the explicit addition of children since it's provided as props to to the component
  * https://github.com/jurassix/react-validation-mixin/blob/master/src/components/validationMixin.js#L120

If you would like to put this in a PR please do. Otherwise I'll make the fix.

**Comment by jurassix** [comment]
Fixed in v5.3.4
