### ISSUE TITLE
Safari/Babel/Webpack Const declarations are not supported in strict mode 

### ISSUE THREAD

**Issue by logandhead** [jurassix/react-validation-mixin#71]
Safari is failing to load my React app with this line:

Const declarations are not supported in strict mode.

This bug occurred after the latest release.

**Comment by jurassix** [comment]
Seems like a packaging issue. However, since this library is transpiled to ES5 via babel I'm not sure where the problem is. Can you inspect your node_modules folder and search for *const*. Also, can you provide the file that is erroring?

I just pulled this library into a new package and searched for *const*, I see results in the README and Test files, but nothing else.

**Comment by royroev** [comment]
Your library has a relationship with joi. These repositories describe the problem and they propose to use the joi-browser. How to take this into account when import your library - the big question.

**Comment by jurassix** [comment]
Note investigation would be needed into the [joi-validation-strategy](https://github.com/jurassix/joi-validation-strategy) since that is the only dependecy on Joi. You can create your own strategy without Joi easily or using joi-browser if you wish.
